# Generated by Django 4.2.6 on 2023-10-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_number', models.IntegerField(primary_key=True, serialize=False)),
                ('num_beds', models.IntegerField()),
                ('smoking', models.BooleanField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
