# Generated by Django 4.2.6 on 2023-10-08 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rename_room_number_roomcost_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='room_number',
            new_name='room',
        ),
    ]
